# ----------------------- #
#      Main Configs       #
# ----------------------- #

name: "Au coin d'une table"
#email: your-email@domain.com
url: http://blog.isammoc.net
description: "Encore un autre blog de développeur"
#baseurl: "/blog" # the subpath of your site, e.g. /blog

# Google Analytics
google_analytics_tracking_id: "UA-25865211-1" # Your Google Analytics ID

permalink: /blog/:year/:month/:day/:title/

# disqus configurations
disqus: true
disqus_shortname: 'isammocsblog'

author:
  name: "Isammoc" # *Required* Display name of the author
  description: > # this means to ignore newlines until email:
    Ingénieur en informatique et formateur sur les outils et méthodes adaptés à la production logicielle.
  # email: your.name@example.com # Email address of the author
  avatar: https://avatars1.githubusercontent.com/u/693554?v=3&s=460
  uri: http://blog.isammoc.net # Webpage where more information about the author can be found
  social:
    - title: github
      url: https://github.com/Isammoc
    - title: stack-overflow
      url: http://stackoverflow.com/users/1380225/isammoc

# jekyll-feed configurations
feed:
  path: atom.xml

# Build settings
markdown: redcarpet

gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%d/%m/%y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml

code_dir: downloads/code
category_dir: blog/categories

titlecase: true       # Converts page and post titles to titlecase

