---
layout: post
title: "Travis CI"
date: 2012-08-05
time: 18:40
comments: true
tags:
- git
- london
- integration continue
- continuous integration
- grails
- travis
categories: project
---

Comme j'utilise github comme dépôt public pour _London Epidemic_, autant utiliser les outils disponibles qui vont bien avec. Je vais donc vous parler de _Travis CI_ une plateforme d'intégration continue pour les dépôts publics de GitHub.

== Intégration continue ?

L'intégration continue est une pratique souvent liée aux méthodologies agiles, mais qui n'en découle pas. Ce serait plutôt les prémisses à mon humble avis.

L'intégration continue consiste à vérifier à chaque commit que le code source fonctionne. Pour cela, les techniques de tests unitaires ou de tests d'intégration automatisées doivent être mises en place dans le projet et les outils d'intégration continue vont exécuter ces tests à chaque fois que le gestionnaire de source (exemple : git) sera mis à jour.

Généralement des rapports ou des alertes sont remontés lorsque les tests échouent, permettant une remontée immédiate dès qu'un souci est rencontré.

== Travis CI

Même si http://jenkins-ci.org/[Jenkins] est reconnu et très souvent utilisé en tant que gestionnaire d'intégration continue, http://travis-ci.org/[Travis] permet la compilation et les tests sans devoir installer une plateforme sur un serveur. En effet, _Travis_ se présente sous la forme d'un service web où l'on s'inscrit avec l'authentification de github, on sélectionne les dépôts que l'on veut qu'il scrute, et l'on configure chaque projet avec un petit fichier `.travis.yml` à la racine de notre projet. Ce fichier permet d'expliquer à _Travis_ comment s'occuper de notre projet.

== Configuration Travis et Grails

Dans le cas dont je me soucie ici, c'est de pouvoir compiler et tester une application grails (_London Epidemic_ en l'occurrence).
Comme _Travis_ n'est pas spécialisé (il peut gérer toute sorte de projet ou presque), il faut configurer la plateforme avant chaque build pour qu'il connaisse grails et la façon dont on lance les tests.

Sans plus de chichis, voici mon fichier : 

[source, yaml, linenums]
----
language: java

jdk: # <1>
  - openjdk7
  - oraclejdk7

before_install: # <2>
 - sudo add-apt-repository -y ppa:groovy-dev/grails
 - sudo apt-get update
 - sudo apt-get -y install grails-ppa
 - sudo apt-get install grails-2.1.0 # or the grails version.

script: grails test-app # <3>
----

Grâce à ce fichier, _Travis_ va tester :

<1> avec deux versions de la jdk différentes (lignes 3 à 5)
<2> installer grails à la version 2.1.0 (lignes 7 à 11)
<3> et lancer les tests (ligne 13).

== Sources
Merci à Bernado (https://twitter.com/berngp[@berngp]) pour son aide à la mise en place du fichier de conf.
